/*
 * Copyright 2025 Karma Krafts & associates
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.karma.kmbed.gradle

import org.intellij.lang.annotations.Language
import java.util.*

internal class SourceBuilder {
    private val builder: StringBuilder = StringBuilder()
    private var indentStack: Stack<Int> = Stack()
    private var currentIndent: Int = 0

    fun append(@Language("kotlin") s: String): SourceBuilder {
        for (i in 0..<currentIndent) {
            builder.append('\t')
        }
        builder.append(s)
        return this
    }

    fun line(@Language("kotlin") s: String): SourceBuilder {
        append("$s\n")
        return this
    }

    fun newline(): SourceBuilder {
        builder.append('\n')
        return this
    }

    fun pushIndent(): SourceBuilder {
        indentStack.push(currentIndent)
        currentIndent++
        return this
    }

    fun pushIndent(indent: Int): SourceBuilder {
        indentStack.push(currentIndent)
        currentIndent = indent
        return this
    }

    fun popIndent(): SourceBuilder {
        currentIndent = indentStack.pop()
        return this
    }

    inline fun indent(closure: SourceBuilder.() -> Unit) {
        pushIndent()
        closure()
        popIndent()
    }

    fun defaultHeader() {
        line("""// Generated by the KMbed resource compiler ${BuildInfo.version}""")
        line("""// !!! DO NOT EDIT THIS FILE BY HAND !!!""")
    }

    fun annotation(name: String): SourceBuilder = line("@$name")

    fun optIn(vararg types: String) {
        if (types.isEmpty()) return
        line("""@OptIn(${types.joinToString(separator = ", ") { "$it::class" }})""")
    }

    fun optIn(types: List<String>) = optIn(*types.toTypedArray())

    fun suppress(vararg warnings: String) {
        if (warnings.isEmpty()) return
        line("""@Suppress(${warnings.joinToString(separator = ", ") { "\"$it\"" }})""")
    }

    fun suppress(warnings: List<String>) = suppress(*warnings.toTypedArray())

    fun pkg(name: String) {
        line("""package $name""")
    }

    fun import(name: String) {
        line("""import $name""")
    }

    fun formatterOff(): SourceBuilder {
        return line("""// @formatter:off""")
    }

    fun formatterOn(): SourceBuilder {
        return line("""// @formatter:on""")
    }

    fun render(): String = builder.toString()
}